export const TOGGLE_LIKE = "TOGGLE-LIKE";

export const ADD_MESSAGE = "ADD-MESSAGE";
export const ADD_POST = "ADD-POST";

export const UNFOLLOW_USER = "UNFOLLOW_USER";
export const FOLLOW_USER = "FOLLOW USER";
export const ADD_USERS = "ADD NEW USERS";
export const NEXT_PAGE = "NEXT PAGE";

export const INPUT_REG = "INPUT_REGISTRATION_FIELD";
export const INPUT_POST = "INPUT_POST";
export const INPUT_LOGIN = "INPUT_LOGIN_FIELD";
export const INPUT_MESSAGE = "INPUT_MESSAGE";

export const START_LOADING = "SHOW LOADING LOOP WHILE DATA DOWNLOAD";
export const STOP_LOADING = "HIDDEN LOADING LOOP WHILE DATA DOWNLOAD";
