export const APP = "APP CONNECT";

export const LOGIN = "LOGIN CONNECT";
export const LOGIN_EMAIL = "LOGIN EMAIL FIELD CONNECT";
export const LOGIN_PASSWORD = "LOGIN PASSWORD FIELD CONNECT";
export const LOGIN_CHECKBOX = "LOGIN CHECKBOX CONNECT";
export const LOGIN_BUTTON = "LOGIN BUTTON CONNECT";

export const REG = "REG CONNECT";
export const REG_PASSWORD = "REG PASSWORD FIELD CONNECT"
export const REG_PASSWORD_AGAIN = "REG PASSWORD AGAIN FIELD CONNECT";
export const REG_EMAIL = "REG EMAIL FIELD CONNECT"
export const REG_FULLNAME = "REG FULLNAME FIELD CONNECT"
export const REG_BUTTON = "REG BUTTON CONNECT"

export const HEADER = "HEADER CONNECT";

export const ME = "ME CONNECT";
export const PROFILE = "PROFILE CONNECT";

export const MAIN = "MAIN CONNECT";

export const NAVIGATION = "NAVIGATION";

export const CREATED_POSTS = "CREATED POSTS LIST CONNECT";
export const MAKE_POST = "MAKE POST CONNECT";
export const LIKE = "LIKE CONNECT";

export const DIALOG = "DIALOG CONNECT";
export const MAKE_MESSAGE = "MAKE MESSAGE CONNECT";
export const MESSAGES = "MESSAGES CONNECT";

export const FRIENDS = "FRIENDS CONNECT";
export const FRIENDS_LIST = "FRIENDS LIST CONNECT";
export const FRIENDS_LIST_ITEM = "FRIENDS LIST ITEM CONNECT";
export const FAVORITE_FRIENDS = "FAVORITE FRIENDS CONNECT";

export const USERS = "USERS CONNECT";
export const USERS_PAGES_LIST = "PAGES LIST CONNECT";
export const USERS_LIST = "USERS LIST CONNECT";
export const USERS_LIST_ITEM = "USERS LIST ITEM";

export const CHECKBOX = "CHECKBOX CONNECT";
