export const AUTH = "SET AUTHORIZE DATA";
export const START_LOADING_AUTH = "START AUTH";
export const END_LOADING_AUTH = "AUTH WAS LOADED";
export const SET_ME = "SET INFO ABOUT ME";
export const START_LOADING_ME = "START LOADING ME";
export const END_LOADING_ME = "END LOADING ME";

export const REG_PASSWORD_INPUT = "INPUT PASSWORD ON REG";
export const REG_PASSWORD_AGAIN_INPUT = "INPUT PASSWORD AGAIN ON REG";
export const REG_FULLNAME_INPUT = "INPUT FULLNAME ON REG";
export const REG_EMAIL_INPUT = "INPUT EMAIL ON REG";

export const LOGIN_EMAIL_INPUT = "INPUT EMAIL ON LOGIN";
export const LOGIN_PASSWORD_INPUT = "INPUT PASSWORD ON LOGIN";
export const LOGIN_CHECKBOX_TOGGLE = "TOGGLE CHECKBOX ON LOGIN";

export const SET_USER_INFO = "USERS LOADED USER INFO";
export const START_LOADING_PROFILE = "START LOADING PROFILE";
export const END_LOADING_PROFILE = "END LOADING PROFILE";

export const TOGGLE_LIKE = "TOGGLE-LIKE";

export const ADD_MESSAGE = "ADD MESSAGE";
export const ADD_POST = "ADD POST";

export const SET_FRIENDS = "SET FRIENDS";
export const NEXT_FRIENDS_PAGE = "NEXT FRIENDS PAGE";
export const START_LOADING_FRIENDS = "START LOADING FRIENDS";
export const END_LOADING_FRIENDS = "END LOADING FRIENDS";
export const END_FOLLOWING_FRIENDS = "END FOLLOWING OR UNFOLLOWING";
export const START_FOLLOWING_FRIENDS = "START FOLLOWING OR UNFOLLOWING";

export const START_FOLLOWING_USER = "START FOLLOWING OR UNFOLLOWING USER";
export const END_FOLLOWING_USER = "END FOLLOWING OR UNFOLLOWING USER";
export const UNFOLLOW_USER = "UNFOLLOW USER";
export const FOLLOW_USER = "FOLLOW USER";
export const ADD_USERS = "ADD NEW USERS";
export const NEXT_USERS_PAGE = "NEXT USERS PAGE";

export const SET_FAVORITE_FRIENDS = "SET LOADED FAVORITE FRIENDS";
export const ADD_FAVORITE_FRIENDS = "ADD FAVORITE FRIENDS MAX CAN BE 6";
export const START_LOADING_FAVORITE_FRIENDS = "START LOADING FAVORITE FRIENDS";
export const END_LOADING_FAVORITE_FRIENDS = "END LOADING FAVORITE FRIENDS";

export const INPUT_POST = "INPUT_POST";
export const INPUT_MESSAGE = "INPUT_MESSAGE";

export const START_LOADING_USERS = "SHOW LOADING LOOP WHILE DATA DOWNLOAD";
export const END_LOADING_USERS = "HIDDEN LOADING LOOP WHILE DATA DOWNLOAD";
